title: Contributing
description: Guidelines for contributing to the Glueful framework
icon: i-heroicons-code-bracket-square
links:
  - label: Getting Started
    to: /contributing
  - label: Code Standards
    to: /contributing/code-standards
  - label: Pull Requests
    to: /contributing/pull-requests
  - label: Documentation
    to: /contributing/documentation
